### ISSUE TITLE
Fix NO DATA intervals on all dashboards

### ISSUE THREAD

**Issue by oopcode** [lidofinance/terra-monitors#18]

**Comment by swelf19** [comment]
i believe problem should be solved with merging https://github.com/lidofinance/terra-monitors/pull/16.
i've increased prometheus's scrape_timeout to 30s(default 10s). For now every request update global index bot monitor takes about 10s to fetch data, which caused timeout error for prometheus and no data at all.
scrape interval increased up to 1m.
