### ISSUE TITLE
Add a monitor that checks whether the bAsset index updating bot is down https://www.notion.so/bAsset-index-updating-bot-f64ebb5ec6704f05a840d93f28b1e3be (with automatic notifications in Tg)

### ISSUE THREAD

**Issue by oopcode** [lidofinance/terra-monitors#2]

**Comment by swelf19** [comment]
I've added the following metrics to UpdateGlobalIndexBotMonitor
update_global_index_successful_tx_since_last_check
update_global_index_failed_tx_since_last_check
update_global_index_gas_wanted
update_global_index_gas_used
update_global_index_uusd_fee
Each metric indicates aggregated changes from last check.
Created grafana dashboard with all 5 metrics on one graph.
